### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle'

### ISSUE THREAD

**Issue by samni728** [Turing-Project/AntiFraudChatBot#15]
(chatbot) root@sambot:/home/samni/chatbot/AntiFraudChatBot-test# python dialog.py 
Traceback (most recent call last):
  File "dialog.py", line 28, in <module>
    import paddlehub as hub
  File "/home/samni/anaconda3/envs/chatbot/lib/python3.7/site-packages/paddlehub/__init__.py", line 18, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'

(chatbot) root@sambot:/home/samni/chatbot/AntiFraudChatBot-test# pip install paddle
Collecting paddle
  Using cached paddle-1.0.2.tar.gz (579 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bx1hmi2i/paddle_1fbbf321c159451885d56f4885f29927/setup.py", line 3, in <module>
          import paddle
        File "/tmp/pip-install-bx1hmi2i/paddle_1fbbf321c159451885d56f4885f29927/paddle/__init__.py", line 5, in <module>
          import common, dual, tight, data, prox
      ModuleNotFoundError: No module named 'common'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for **details.**

请问这个问题如何解决 谢谢

**Comment by samni728** [comment]
Python 3.7.15 (default, Nov 24 2022, 21:12:53) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddlehub
Illegal instruction (core dumped)
