### ISSUE TITLE
ibase 未知异常

### ISSUE THREAD

**Issue by SK-Keith** [Turing-Project/AntiFraudChatBot#6]
[2022-12-12 18:05:40,513] ERROR in app: Exception on /translate [POST]
Traceback (most recent call last):
  File "D:\soft\python3.9.5\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\soft\python3.9.5\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\soft\python3.9.5\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\soft\python3.9.5\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:\workspacePy\weichat2\Yuan-1.0\Sandbox\api\demo_web_app.py", line 104, in translate
    response = gpt.submit_API(prompt=prompt, trun=gpt.output_suffix)
  File "D:\workspacePy\weichat2\Yuan-1.0\Sandbox\api\inspurai.py", line 164, in submit_API
    res = self.response(query,engine=self.engine,
  File "D:\workspacePy\weichat2\Yuan-1.0\Sandbox\api\inspurai.py", line 147, in response
    raise e
  File "D:\workspacePy\weichat2\Yuan-1.0\Sandbox\api\inspurai.py", line 143, in response
    requestId = submit_request(query, temperature, topP, topK, max_tokens, engine, frequencyPenalty,
  File "D:\workspacePy\weichat2\Yuan-1.0\Sandbox\api\url_config.py", line 55, in submit_request
    raise  RuntimeWarning(response_text)
RuntimeWarning: {'flag': False, 'errCode': 'IBASE_CONTROLLER_UNKNOWN_EXCEPTION', 'errMessage': 'ibase 未知异常', 'exceptionMsg': 'IBASE_INTERFACE_GET_USER_INTERFACE_EMPTY', 'resData': None}

**Comment by SK-Keith** [comment]
看了yuan官网，应该是帐号没有申请开通API使用权限

**Comment by XingYuan55** [comment]
如何获取API使用权限啊
